from case import *
from piece import *


def position_starting_game(screen): #fonction de blitt de toutes les positions de départ
    case[0][0].blit(W_rook, (0, 0))
    screen.blit(case[0][0], coord_case[0][0])
    case[0][1].blit(W_pawn, (0, 0))
    screen.blit(case[0][1], coord_case[0][1])
    case[0][6].blit(B_pawn, (0, 0))
    screen.blit(case[0][6], coord_case[0][6])
    case[0][7].blit(B_rook, (0, 0))
    screen.blit(case[0][7], coord_case[0][7])

    case[1][0].blit(W_knight, (0, 0))
    screen.blit(case[1][0], coord_case[1][0])
    case[1][1].blit(W_pawn, (0, 0))
    screen.blit(case[1][1], coord_case[1][1])
    case[1][6].blit(B_pawn, (0, 0))
    screen.blit(case[1][6], coord_case[1][6])
    case[1][7].blit(B_knight, (0, 0))
    screen.blit(case[1][7], coord_case[1][7])

    case[2][0].blit(W_bishop, (0, 0))
    screen.blit(case[2][0], coord_case[2][0])
    case[2][1].blit(W_pawn, (0, 0))
    screen.blit(case[2][1], coord_case[2][1])
    case[2][6].blit(B_pawn, (0, 0))
    screen.blit(case[2][6], coord_case[2][6])
    case[2][7].blit(B_bishop, (0, 0))
    screen.blit(case[2][7], coord_case[2][7])

    case[3][0].blit(W_queen, (0, 0))
    screen.blit(case[3][0], coord_case[3][0])
    case[3][1].blit(W_pawn, (0, 0))
    screen.blit(case[3][1], coord_case[3][1])
    case[3][6].blit(B_pawn, (0, 0))
    screen.blit(case[3][6], coord_case[3][6])
    case[3][7].blit(B_queen, (0, 0))
    screen.blit(case[3][7], coord_case[3][7])

    case[4][0].blit(W_king, (0, 0))
    screen.blit(case[4][0], coord_case[4][0])
    case[4][1].blit(W_pawn, (0, 0))
    screen.blit(case[4][1], coord_case[4][1])
    case[4][6].blit(B_pawn, (0, 0))
    screen.blit(case[4][6], coord_case[4][6])
    case[4][7].blit(B_king, (0, 0))
    screen.blit(case[4][7], coord_case[4][7])

    case[5][0].blit(W_bishop, (0, 0))
    screen.blit(case[5][0], coord_case[5][0])
    case[5][1].blit(W_pawn, (0, 0))
    screen.blit(case[5][1], coord_case[5][1])
    case[5][6].blit(B_pawn, (0, 0))
    screen.blit(case[5][6], coord_case[5][6])
    case[5][7].blit(B_bishop, (0, 0))
    screen.blit(case[5][7], coord_case[5][7])

    case[6][0].blit(W_knight, (0, 0))
    screen.blit(case[6][0], coord_case[6][0])
    case[6][1].blit(W_pawn, (0, 0))
    screen.blit(case[6][1], coord_case[6][1])
    case[6][6].blit(B_pawn, (0, 0))
    screen.blit(case[6][6], coord_case[6][6])
    case[6][7].blit(B_knight, (0, 0))
    screen.blit(case[6][7], coord_case[6][7])

    case[7][0].blit(W_rook, (0, 0))
    screen.blit(case[7][0], coord_case[7][0])
    case[7][1].blit(W_pawn, (0, 0))
    screen.blit(case[7][1], coord_case[7][1])
    case[7][6].blit(B_pawn, (0, 0))
    screen.blit(case[7][6], coord_case[7][6])
    case[7][7].blit(B_rook, (0, 0))
    screen.blit(case[7][7], coord_case[7][7])


