from case import chessboard,coord_case
from piece import *


def position_starting_game(screen): #fonction de blitt de toutes les positions de départ et prise de couleur pour chaque case
    chessboard[0][0].surface.blit(W_rook.get_sprite(), (0, 0))
    chessboard[0][0].color = W_rook.get_color()
    chessboard[0][0].piece = W_rook.get_name()
    screen.blit(chessboard[0][0].surface, coord_case[0][0])
    chessboard[0][1].surface.blit(W_pawn.get_sprite(), (0, 0))
    chessboard[0][1].color = W_pawn.get_color()
    chessboard[0][1].piece = W_pawn.get_name()
    screen.blit(chessboard[0][1].surface, coord_case[0][1])
    chessboard[0][6].surface.blit(B_pawn.get_sprite(), (0, 0))
    chessboard[0][6].color = B_pawn.get_color()
    chessboard[0][6].piece = B_pawn.get_name()
    screen.blit(chessboard[0][6].surface, coord_case[0][6])
    chessboard[0][7].surface.blit(B_rook.get_sprite(), (0, 0))
    chessboard[0][7].color = B_rook.get_color()
    chessboard[0][7].piece = B_rook.get_name()
    screen.blit(chessboard[0][7].surface, coord_case[0][7])

    chessboard[1][0].surface.blit(W_knight.get_sprite(), (0, 0))
    chessboard[1][0].color = W_knight.get_color()
    chessboard[1][0].piece = W_knight.get_name()
    screen.blit(chessboard[1][0].surface, coord_case[1][0])
    chessboard[1][1].surface.blit(W_pawn.get_sprite(), (0, 0))
    chessboard[1][1].color = W_pawn.get_color()
    chessboard[1][1].piece = W_pawn.get_name()
    screen.blit(chessboard[1][1].surface, coord_case[1][1])
    chessboard[1][6].surface.blit(B_pawn.get_sprite(), (0, 0))
    chessboard[1][6].color = B_pawn.get_color()
    chessboard[1][6].piece = B_pawn.get_name()
    screen.blit(chessboard[1][6].surface, coord_case[1][6])
    chessboard[1][7].surface.blit(B_knight.get_sprite(), (0, 0))
    chessboard[1][7].color = B_knight.get_color()
    chessboard[1][7].piece = B_knight.get_name()
    screen.blit(chessboard[1][7].surface, coord_case[1][7])

    chessboard[2][0].surface.blit(W_bishop.get_sprite(), (0, 0))
    chessboard[2][0].color = W_bishop.get_color()
    chessboard[2][0].piece = W_bishop.get_name()
    screen.blit(chessboard[2][0].surface, coord_case[2][0])
    chessboard[2][1].surface.blit(W_pawn.get_sprite(), (0, 0))
    chessboard[2][1].color = W_pawn.get_color()
    chessboard[2][1].piece = W_pawn.get_name()
    screen.blit(chessboard[2][1].surface, coord_case[2][1])
    chessboard[2][6].surface.blit(B_pawn.get_sprite(), (0, 0))
    chessboard[2][6].color = B_pawn.get_color()
    chessboard[2][6].piece = B_pawn.get_name()
    screen.blit(chessboard[2][6].surface, coord_case[2][6])
    chessboard[2][7].surface.blit(B_bishop.get_sprite(), (0, 0))
    chessboard[2][7].color = B_bishop.get_color()
    chessboard[2][7].piece = B_bishop.get_name()
    screen.blit(chessboard[2][7].surface, coord_case[2][7])

    chessboard[3][0].surface.blit(W_queen.get_sprite(), (0, 0))
    chessboard[3][0].color = W_queen.get_color()
    chessboard[3][0].piece = W_queen.get_name()
    screen.blit(chessboard[3][0].surface, coord_case[3][0])
    chessboard[3][1].surface.blit(W_pawn.get_sprite(), (0, 0))
    chessboard[3][1].color = W_pawn.get_color()
    chessboard[3][1].piece = W_pawn.get_name()
    screen.blit(chessboard[3][1].surface, coord_case[3][1])
    chessboard[3][6].surface.blit(B_pawn.get_sprite(), (0, 0))
    chessboard[3][6].color = B_pawn.get_color()
    chessboard[3][6].piece = B_pawn.get_name()
    screen.blit(chessboard[3][6].surface, coord_case[3][6])
    chessboard[3][7].surface.blit(B_queen.get_sprite(), (0, 0))
    chessboard[3][7].color = B_queen.get_color()
    chessboard[3][7].piece = B_queen.get_name()
    screen.blit(chessboard[3][7].surface, coord_case[3][7])

    chessboard[4][0].surface.blit(W_king.get_sprite(), (0, 0))
    chessboard[4][0].color = W_king.get_color()
    chessboard[4][0].piece = W_king.get_name()
    screen.blit(chessboard[4][0].surface, coord_case[4][0])
    chessboard[4][1].surface.blit(W_pawn.get_sprite(), (0, 0))
    chessboard[4][1].color = W_pawn.get_color()
    chessboard[4][1].piece = W_pawn.get_name()
    screen.blit(chessboard[4][1].surface, coord_case[4][1])
    chessboard[4][6].surface.blit(B_pawn.get_sprite(), (0, 0))
    chessboard[4][6].color = B_pawn.get_color()
    chessboard[4][6].piece = B_pawn.get_name()
    screen.blit(chessboard[4][6].surface, coord_case[4][6])
    chessboard[4][7].surface.blit(B_king.get_sprite(), (0, 0))
    chessboard[4][7].color = B_king.get_color()
    chessboard[4][7].piece = B_king.get_name()
    screen.blit(chessboard[4][7].surface, coord_case[4][7])

    chessboard[5][0].surface.blit(W_bishop.get_sprite(), (0, 0))
    chessboard[5][0].color = W_bishop.get_color()
    chessboard[5][0].piece = W_bishop.get_name()
    screen.blit(chessboard[5][0].surface, coord_case[5][0])
    chessboard[5][1].surface.blit(W_pawn.get_sprite(), (0, 0))
    chessboard[5][1].color = W_pawn.get_color()
    chessboard[5][1].piece = W_pawn.get_name()
    screen.blit(chessboard[5][1].surface, coord_case[5][1])
    chessboard[5][6].surface.blit(B_pawn.get_sprite(), (0, 0))
    chessboard[5][6].color = B_pawn.get_color()
    chessboard[5][6].piece = B_pawn.get_name()
    screen.blit(chessboard[5][6].surface, coord_case[5][6])
    chessboard[5][7].surface.blit(B_bishop.get_sprite(), (0, 0))
    chessboard[5][7].color = B_bishop.get_color()
    chessboard[5][7].piece = B_bishop.get_name()
    screen.blit(chessboard[5][7].surface, coord_case[5][7])

    chessboard[6][0].surface.blit(W_knight.get_sprite(), (0, 0))
    chessboard[6][0].color = W_knight.get_color()
    chessboard[6][0].piece = W_knight.get_name()
    screen.blit(chessboard[6][0].surface, coord_case[6][0])
    chessboard[6][1].surface.blit(W_pawn.get_sprite(), (0, 0))
    chessboard[6][1].color = W_pawn.get_color()
    chessboard[6][1].piece = W_pawn.get_name()
    screen.blit(chessboard[6][1].surface, coord_case[6][1])
    chessboard[6][6].surface.blit(B_pawn.get_sprite(), (0, 0))
    chessboard[6][6].color = B_pawn.get_color()
    chessboard[6][6].piece = B_pawn.get_name()
    screen.blit(chessboard[6][6].surface, coord_case[6][6])
    chessboard[6][7].surface.blit(B_knight.get_sprite(), (0, 0))
    chessboard[6][7].color = B_knight.get_color()
    chessboard[6][7].piece = B_knight.get_name()
    screen.blit(chessboard[6][7].surface, coord_case[6][7])

    chessboard[7][0].surface.blit(W_rook.get_sprite(), (0, 0))
    chessboard[7][0].color = W_rook.get_color()
    chessboard[7][0].piece = W_rook.get_name()
    screen.blit(chessboard[7][0].surface, coord_case[7][0])
    chessboard[7][1].surface.blit(W_pawn.get_sprite(), (0, 0))
    chessboard[7][1].color = W_pawn.get_color()
    chessboard[7][1].piece = W_pawn.get_name()
    screen.blit(chessboard[7][1].surface, coord_case[7][1])
    chessboard[7][6].surface.blit(B_pawn.get_sprite(), (0, 0))
    chessboard[7][6].color = B_pawn.get_color()
    chessboard[7][6].piece = B_pawn.get_name()
    screen.blit(chessboard[7][6].surface, coord_case[7][6])
    chessboard[7][7].surface.blit(B_rook.get_sprite(), (0, 0))
    chessboard[7][7].color = B_rook.get_color()
    chessboard[7][7].piece = B_rook.get_name()
    screen.blit(chessboard[7][7].surface, coord_case[7][7])


